services:
  swagger:
    container_name: rucQ_swagger
    image: swaggerapi/swagger-ui:v5.18.2
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - type: bind
        source: ./
        target: /openapi/
