openapi: 3.0.3

info:
  title: rucQ API
  version: 0.1.0
  description: rucQ API

servers:
  - url: http://localhost:8080
    description: 開発環境

paths:
  /api/events:
    get:
      summary: イベントの一覧を取得
      tags:
        - Events
      operationId: getEvents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetEventResponse'
    post:
      summary: イベントを作成
      tags:
        - Events
      operationId: postEvent
      parameters:
        - $ref: '#/components/parameters/X-Forwarded-User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostEventRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEventResponse'
  /api/me:
    get:
      summary: 自分の情報を取得
      tags:
        - Users
      operationId: getMe
      parameters:
        - $ref: '#/components/parameters/X-Forwarded-User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'

components:
  parameters:
    X-Forwarded-User:
      name: X-Forwarded-User
      in: header
      description: ログインしているユーザーのtraQ ID（NeoShowcaseが自動で付与）
      required: true
      schema:
        type: string
  schemas:
    GetEventResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        location:
          type: string
        time_start:
          type: string
          format: date-time
        time_end:
          type: string
          format: date-time
        camp_id:
          type: integer
        organizer_traq_id:
          type: string
      required:
        - id
        - name
        - description
        - location
        - time_start
        - time_end
        - camp_id
        - organizer_traq_id
    PostEventRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        location:
          type: string
        time_start:
          type: string
          format: date-time
        time_end:
          type: string
          format: date-time
        camp_id:
          type: integer
        create_as_staff:
          type: boolean
      required:
        - name
        - description
        - location
        - time_start
        - time_end
        - camp_id
        - create_as_staff
    GetUserResponse:
      type: object
      properties:
        traq_id:
          type: string
        is_staff:
          type: boolean
      required:
        - traq_id
        - is_staff

tags:
  - name: Events
    description: Event API
  - name: Users
    description: User API
